default:
  image: python:latest
  tags:
    - "docker-alpine"
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip


stages:
  - build
  - test
  - deploy

before_script:
  - python --version ; pip --version
  - ls
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate


build:
  stage: build
  script:
    - python setup.py sdist bdist_wheel

test:
  stage: test
  script:
    - pip install .
    - python -m unittest discover tests

deploy to package registry:
  stage: deploy
  script:
    - pip install setuptools wheel
    - pip install twine
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  artifacts:
    paths:
      - dist/*.whl
    expire_in: 2 days